---
includes:
    [
        src/protos/datafeed,
        src/protos/order,
        src/protos/algo,
        src/protos/app,
        src/protos/pnl,
        src/protos/broker,
        src/protos/service/messages,
        src/protos/service/types,
    ]
files:
    [
        "src/protos/datafeed/candle.proto",
        "src/protos/order/order.proto",
        "src/protos/order/order_list.proto",
        "src/protos/algo/advice.proto",
        "src/protos/broker/order_filled.proto",
        "src/protos/datafeed/tick.proto",
        "src/protos/datafeed/historical_data.proto",
        "src/protos/service/types/datafeed_stream.proto",
        "src/protos/service/messages/start_datafeed.proto",
        "src/protos/service/messages/start_algo.proto",
        "src/protos/service/messages/start_broker.proto",
        "src/protos/service/messages/join_datafeed.proto",
        "src/protos/service/messages/join_datafeed_success.proto",
        "src/protos/service/messages/join_algofeed.proto",
        "src/protos/service/messages/join_algofeed_success.proto",
        "src/protos/service/messages/join_orderfeed.proto",
        "src/protos/service/messages/join_orderfeed_success.proto",
        "src/protos/service/messages/join_overall_pnlfeed.proto",
        "src/protos/service/messages/join_strategy_pnlfeed.proto",
        "src/protos/service/messages/join_loggerfeed.proto",
        "src/protos/service/messages/join_overall_pnlfeed_success.proto",
        "src/protos/service/messages/join_strategy_pnlfeed_success.proto",
        "src/protos/service/types/message_type.proto",
        "src/protos/datafeed/ohlcv.proto",
        "src/protos/algo/value.proto",
        "src/protos/algo/line.proto",
        "src/protos/algo/point.proto",
        "src/protos/algo/rectangle.proto",
        "src/protos/datafeed/datafeed_complete.proto",
        "src/protos/algo/algo_complete.proto",
        "src/protos/broker/broker_complete.proto",
        "src/protos/order/orderfeed_complete.proto",
        "src/protos/pnl/pnl_complete.proto",
        "src/protos/pnl/overall_pnl_complete.proto",
        "src/protos/service/types/network.proto",
        "src/protos/service/types/topic.proto",
        "src/protos/service/messages/abort_algo_subscriber.proto",
        "src/protos/service/messages/abort_logger_subscriber.proto",
        "src/protos/service/messages/abort_broker_subscriber.proto",
        "src/protos/service/messages/abort_advice_subscriber.proto",
        "src/protos/pnl/realized.proto",
        "src/protos/pnl/unrealized.proto",
        "src/protos/service/messages/app_request.proto",
        "src/protos/service/messages/app_response.proto",
        "src/protos/app/chart.proto",
        "src/protos/service/messages/chart_request.proto",
        "src/protos/app/algo_chart.proto",
        "src/protos/app/total_pnl.proto",
        "src/protos/app/total_pnl_realized.proto",
        "src/protos/app/total_pnl_unrealized.proto",
        "src/protos/app/pos_pnl_realized.proto",
        "src/protos/app/pos_pnl_realized_list.proto",
        "src/protos/app/pos_pnl_unrealized.proto",
        "src/protos/pnl/position_stats.proto",
        "src/protos/app/overall_stats.proto",
        "src/protos/pnl/overall_day_stats.proto",
        "src/protos/pnl/overall_day_stats_list.proto",
        "src/protos/service/messages/log_request.proto",
        "src/protos/service/messages/read_from_dir_response.proto",
        "src/protos/service/messages/read_from_dir_request.proto",
        "src/protos/service/types/symbol_period.proto",
        "src/protos/service/types/strategy.proto",
        "src/protos/service/messages/strategy_list.proto",
        "src/protos/service/messages/strategy_from_log_request.proto",
        "src/protos/service/messages/overall_from_log_request.proto",
        "src/protos/service/messages/run_strategy.proto",
        "src/protos/service/messages/service_available_request.proto",
        "src/protos/service/messages/service_available_response.proto",
        "src/protos/service/messages/start_batch.proto",
        "src/protos/service/types/batch.proto",
        "src/protos/service/messages/abort_overall_pnl_subscriber.proto",
        "src/protos/service/messages/abort_strategy_pnl_subscriber.proto",
        "src/protos/service/messages/start_ninja_datafeed.proto",
        "src/protos/service/messages/join_ninjafeed.proto",
        "src/protos/service/messages/start_ninja_orderfeed.proto",
        "src/protos/app/pnl_calendar.proto",
        "src/protos/app/pnl_hour.proto",
        "src/protos/service/messages/overall_request.proto",
        "src/protos/service/messages/run_yaml.proto",
    ]
messages:
    - paths:
          [
              Candle,
              Order,
              Tick,
              HistoricalData,
              RunStrategy,
              StopStrategy,
              DatafeedStream,
              MessageType,
              HistoricalDataConfig,
              Ohlcv,
              Network,
              Line,
              Value,
              Point,
              CandleStream,
              AppRequest,
              AppResponse,
              JoinAlgofeed,
              JoinDatafeed,
              Topic,
              Chart,
              ChartRequest,
              JoinChartfeed,
              OrderList,
              Rectangle,
              Rectangles,
              Advice,
              AlgoChart,
              OrderStatusUpdate,
              OrderFilled,
              TotalPnl,
              TotalPnlRealized,
              TotalPnlUnrealized,
              PositionPnlRealized,
              PositionPnlUnrealized,
              PositionStats,
              LogRequest,
              ReadFromDirRequest,
              ReadFromDirResponse,
              SymbolPeriods,
              Strategy,
              ChartfeedStrategy,
              StrategyList,
              StrategyFromLogRequest,
              OverallStats,
              OverallDayStats,
              ServiceAvailableRequest,
              ServiceAvailableResponse,
              JoinOrderfeed,
              JoinOrderfeedSuccess,
              OrderfeedComplete,
              ChartfeedBatch,
              Batch,
              AbortOverallPnlSubscriber,
              StartBatch,
              JoinOverallPnlfeed,
              JoinLoggerfeed,
              PnlCalendar,
              PnlHour,
              PositionPnlRealizedList,
              BrokerComplete,
              StartBroker,
              StartAlgo,
              StartDatafeed,
              PnlValue,
              OverallDayStatsList,
          ]
      attrs:
          - derive(serde::Serialize, serde::Deserialize)
enums:
    - paths: [DatafeedProvider, OrderType, AlgoId, DatafeedType, BrokerId, ExecutionMode]
      attrs:
          - derive(serde::Serialize, serde::Deserialize, strum_macros::Display)
fields:
    - paths: []
      attrs:
          - validate(email)
btree_map: ["."]
bytes: ["."]
